'ðŸš¦ status: awaiting approval':
  issues:
    comment: >
      To reduce notifications, issues are locked until they are valid/approved and to be assigned. In the meantime read the contributing guidelines -> https://github.com/Dun-sin/Whisper/blob/main/CONTRIBUTING.md
    unlock: true
    lock: true

'ðŸ status: ready for dev':
  issues:
    comment: >
      The issue has been unlocked and is now ready for dev. If you would like to work on this issue, you can comment to have it assigned to you.
    unlock: true
